"""
Django settings for reddit_persona_app project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# reddit_persona_app/settings.py

from pathlib import Path
import os # <--- ADDED: Needed for os.environ.get and static files setup

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$)(0jzjes#x57k41o-ej$$%3o7uou^@pr16%y1nm(^bhbtrgz*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'persona_generator', # Your newly created app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reddit_persona_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Kept as is from your provided settings
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reddit_persona_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ # <--- ADDED: This is crucial for Django to find your app's static files
    os.path.join(BASE_DIR, 'persona_generator', 'static'),
]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Uncomment and run collectstatic in production


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- API KEYS AND CREDENTIALS (THESE WERE MISSING) ---

# LLM API Key (IMPORTANT: Use environment variables in production for security!)
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', 'AIzaSyCbHPob0iNpgwPlwEYJoN-7HmPk4ItMUb8') # Replace 'YOUR_GEMINI_API_KEY' with your actual key

## Reddit API Credentials
REDDIT_CLIENT_ID = os.environ.get('REDDIT_CLIENT_ID','Crz8YtoTlj9nrL5FC9gsEA') # <--- Check this
REDDIT_CLIENT_SECRET = os.environ.get('REDDIT_CLIENT_SECRET','XEgVVOPqWALHvNAbjEN-SiFztBstSA') # <--- Check this
REDDIT_USER_AGENT = os.environ.get('REDDIT_USER_AGENT','PersonaGeneratorApp/1.0 (by mohit)') # <--- Check this