# Generated by Django 5.1.5 on 2025-07-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_username', models.CharField(help_text='Reddit username for which the persona was generated.', max_length=255, unique=True)),
                ('persona_text', models.TextField(help_text='The full generated user persona text.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(help_text='A specific characteristic of the persona.', max_length=500)),
                ('citations', models.TextField(help_text="JSON string of cited Reddit posts/comments (e.g., [{'url': '...', 'snippet': '...'}])")),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='persona_generator.persona')),
            ],
            options={
                'verbose_name_plural': 'Persona Characteristics',
            },
        ),
    ]
